```{r setup, include=FALSE}
library(plotly)
library(dplyr)
library(htmlwidgets)
```

```{r}
eq_data<-read.csv("eqarchive-en.csv")
head(data)
```

Since the year 2000, there has been a noticeable trend of increasing earthquake frequency each year, and the year 2000 marked the first year when the cumulative earthquake count exceeded 2,000.
```{r}
frequency <- data %>%
  group_by(year = format(date, "%Y")) %>%
  summarise(count = n())
frequency$year <- as.numeric(frequency$year)

ggplot(data = frequency, aes(x = year, y = count)) +
  geom_bar(stat = "identity", fill = "blue", width = 0.7) +
  labs(title = "Number of earthquakes in each year", x = "Year", y = "Number of earthquakes")
```

```{r}
#delete the information from 1985 - 1999
eq_data$date <- as.POSIXct(data$date, format = "%Y-%m-%dT%H:%M:%S%z")
data2 <- subset(data, date >= as.POSIXct("2000-01-01T04:00:00+0000", format = "%Y-%m-%dT%H:%M:%S%z"))
data2
```

```{r}
#Dividing the magnitude into 7 levels 
breaks <- c(-Inf, 1, 3, 4.5, 6, 7, 8, Inf)
categories <- cut(data2$magnitude, breaks = breaks)
magnitude_level <- table(categories)
magnitude_level_df <- data.frame(
  Magnitude_Range = as.character(names(magnitude_level)),
  Earthquake_Count = as.numeric(magnitude_level)
)
print(magnitude_level_df)
```

```{r}
#Calculating the percentages for different earthquake magnitude's levels
percentages <- (magnitude_level_df$Earthquake_Count / sum(magnitude_level_df$Earthquake_Count))*100
A <- as.data.frame(percentages)

#Draw the pie chart of the percentage
piechart <- plot_ly(A, labels=~magnitude_level_df$Magnitude_Range, values=~percentages, type="pie", width = 500, height = 400)%>% 
  layout(margin=list(l=0, r=0, b=0, t=20),
         title = list(text="Pie Chart of Magnitude levels", font=list(size=10)),
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         legend = list(title = list(text="Magnitude levels"),font=list(size=10))
  )
piechart
```

